-- AlterTable
ALTER TABLE "Cat" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "name" DROP DEFAULT,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "picture_url" DROP NOT NULL,
ALTER COLUMN "picture_url" DROP DEFAULT;
